### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by oritselaye**

### CODE REVIEW

**Comment by Victorayo** [comment]
@oritselaye I catch you this time co-contributor 🙃.

**Comment by OSCA-Ado-Ekiti** [comment]
@oritselaye did you also add this company to the techCompanies.js file?

**Comment by oritselaye** [comment]
No, I didn't

**Comment by OSCA-Ado-Ekiti** [comment]
@oritselaye Please add it and make sure your PR is free from conflicts

**Pull request closed without merging**
