### PR TITLE
Feat/build website

### LINKED ISSUE #15: Website link not working
When I click on the web link, it takes me to a 404 page.

### PR DESCRIPTION
**Pull request by Timonwa**
I built a website for Tech Companies in Africa. You can preview it [here](https://tech-companies-in-africa.vercel.app):

## Corrections/modifications a made:
- I created a .js file for the tech companies' data and imported it as a module to use to create the company cards instead of using the .json file as it wasn't feasible to fetch the data from the .json file.
- I also edited some of the company's data as some of the names or websites were incorrect and rearranged them alphabetically.
- I updated the contributing.md file also to reflect the changes made so contributors can know which files to add the company details to.
- I also added an MIT license.

## Comments
- The tech company data in the readme file would need updating as I only made corrections to the .json file.

Please let me know if you would like any modifications or additions made to the website.

this closes #15.

### CODE REVIEW

**Comment by OSCA-Ado-Ekiti** [comment]
This is great @Timonwa, am impreased, wow, wow

**Comment by OSCA-Ado-Ekiti** [comment]
How does the live app gets updated whenever a new contribution is made?

**Comment by Timonwa** [comment]
It automatically updates itself. As far as the data is inserted correctly into the array in the techCompanies.js file, it will run smoothly. 

I don't have access to set the website to show through your link though; (osca-ado-ekiti.github.io/tech-companies-in-africa/). So that would have to be done from your end.

**Comment by OSCA-Ado-Ekiti** [comment]
Let me grant you permission to the repo, also i think your link is okay, can we just replace our link with your vercel generated link?

**Comment by Timonwa** [comment]
Yeah sure, you can use my link also.

**Comment by Timonwa** [comment]
Hi. Good day, I noticed that the website link is still not work.

**Comment by OSCA-Ado-Ekiti** [comment]
We have fixed it, thanks so uch, deployed to vercel and the links have been updated

**Comment by Timonwa** [comment]
Cool.

**Comment by OSCA-Ado-Ekiti** [comment]
Thank you 😊

**Pull request merged**
